# -*- coding: utf-8 -*-
"""Emotionprediction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15QyTUCHh02LqsFgQeXev57Ftifoserdb
"""

# !pip install ktrain

from google.colab import drive
drive.mount('/content/drive')

#import libraries
import pandas as pd
import numpy as np
import ktrain
import tensorflow as tf
from ktrain import text
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings("ignore")

predictor1 = ktrain.load_predictor('/content/drive/MyDrive/Empathetic_Mental_Health_Chatbot/Data Preparation/Emotion_detection_model')

#right prediction
inp1="I was shocked when I found out that my cousin was having a kid."
predictor1.predict(inp1)
#excited

#right prediction
inp2="I'm glad the weekend is finally here."
predictor1.predict(inp2)
#excited

imp3 ="seeing a little kid crying at the store i decided to ask what was wrong"
predictor1.predict(imp3)

imp4 ="I am sad"
predictor1.predict(imp4)

imp4 ="I am feeling depressed"
predictor1.predict(imp4)

inp6=input()
predictor1.predict(inp6)

